create extension if not exists postgis;

create table if not exists usuarios (
  id integer generated by default as identity primary key,
  firebase_uid varchar(255),
  email varchar(255) not null,
  nombre varchar(150) not null,
  rol varchar(20) not null default 'ciudadano',
  activo boolean not null default true,
  password_hash varchar(255),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table usuarios add column if not exists firebase_uid varchar(255);
alter table usuarios add column if not exists email varchar(255);
alter table usuarios add column if not exists nombre varchar(150);
alter table usuarios add column if not exists rol varchar(20) default 'ciudadano';
alter table usuarios add column if not exists activo boolean default true;
alter table usuarios add column if not exists password_hash varchar(255);
alter table usuarios add column if not exists created_at timestamptz default now();
alter table usuarios add column if not exists updated_at timestamptz default now();

create table if not exists categorias (
  id integer generated by default as identity primary key,
  nombre varchar(50) not null,
  descripcion text,
  activo boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table categorias add column if not exists nombre varchar(50);
alter table categorias add column if not exists descripcion text;
alter table categorias add column if not exists activo boolean default true;
alter table categorias add column if not exists created_at timestamptz default now();
alter table categorias add column if not exists updated_at timestamptz default now();

create table if not exists zonas (
  id integer generated by default as identity primary key,
  nombre varchar(100) not null,
  descripcion text,
  geom geometry(Polygon, 4326),
  activo boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table zonas add column if not exists nombre varchar(100);
alter table zonas add column if not exists descripcion text;
alter table zonas add column if not exists geom geometry(Polygon, 4326);
alter table zonas add column if not exists activo boolean default true;
alter table zonas add column if not exists created_at timestamptz default now();
alter table zonas add column if not exists updated_at timestamptz default now();

create table if not exists reportes (
  id integer generated by default as identity primary key,
  usuario_id integer not null,
  categoria_id integer not null,
  zona_id integer,
  urgencia varchar(10) not null,
  descripcion text not null,
  ubicacion geometry(Point, 4326) not null,
  direccion_aprox varchar(300),
  estado varchar(20) not null default 'pendiente',
  validado_por integer,
  validado_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table reportes add column if not exists usuario_id integer;
alter table reportes add column if not exists categoria_id integer;
alter table reportes add column if not exists zona_id integer;
alter table reportes add column if not exists urgencia varchar(10);
alter table reportes add column if not exists descripcion text;
alter table reportes add column if not exists ubicacion geometry(Point, 4326);
alter table reportes add column if not exists direccion_aprox varchar(300);
alter table reportes add column if not exists estado varchar(20) default 'pendiente';
alter table reportes add column if not exists validado_por integer;
alter table reportes add column if not exists validado_at timestamptz;
alter table reportes add column if not exists created_at timestamptz default now();
alter table reportes add column if not exists updated_at timestamptz default now();

create table if not exists reporte_fotos (
  id integer generated by default as identity primary key,
  reporte_id integer not null,
  ruta_relativa varchar(500) not null,
  descripcion text,
  created_at timestamptz not null default now()
);

alter table reporte_fotos add column if not exists reporte_id integer;
alter table reporte_fotos add column if not exists ruta_relativa varchar(500);
alter table reporte_fotos add column if not exists descripcion text;
alter table reporte_fotos add column if not exists created_at timestamptz default now();

create table if not exists historial_reportes (
  id integer generated by default as identity primary key,
  reporte_id integer not null,
  usuario_id integer,
  accion varchar(50) not null,
  estado_anterior varchar(20),
  estado_nuevo varchar(20),
  comentario text,
  created_at timestamptz not null default now()
);

alter table historial_reportes add column if not exists reporte_id integer;
alter table historial_reportes add column if not exists usuario_id integer;
alter table historial_reportes add column if not exists accion varchar(50);
alter table historial_reportes add column if not exists estado_anterior varchar(20);
alter table historial_reportes add column if not exists estado_nuevo varchar(20);
alter table historial_reportes add column if not exists comentario text;
alter table historial_reportes add column if not exists created_at timestamptz default now();

create table if not exists analisis_kde (
  id integer generated by default as identity primary key,
  fecha_calculo timestamptz not null default now(),
  periodo_inicio date,
  periodo_fin date,
  categoria_id integer,
  zona_id integer,
  total_reportes integer not null default 0,
  resultado_json jsonb not null default '{}'::jsonb,
  geom_hull geometry(Polygon, 4326)
);

alter table analisis_kde add column if not exists fecha_calculo timestamptz default now();
alter table analisis_kde add column if not exists periodo_inicio date;
alter table analisis_kde add column if not exists periodo_fin date;
alter table analisis_kde add column if not exists categoria_id integer;
alter table analisis_kde add column if not exists zona_id integer;
alter table analisis_kde add column if not exists total_reportes integer default 0;
alter table analisis_kde add column if not exists resultado_json jsonb default '{}'::jsonb;
alter table analisis_kde add column if not exists geom_hull geometry(Polygon, 4326);

create table if not exists indicadores_reportes (
  id integer generated by default as identity primary key,
  fecha date not null,
  categoria_id integer,
  zona_id integer,
  total_reportes integer not null default 0,
  total_validados integer not null default 0,
  total_rechazados integer not null default 0,
  total_pendientes integer not null default 0,
  created_at timestamptz not null default now()
);

alter table indicadores_reportes add column if not exists fecha date;
alter table indicadores_reportes add column if not exists categoria_id integer;
alter table indicadores_reportes add column if not exists zona_id integer;
alter table indicadores_reportes add column if not exists total_reportes integer default 0;
alter table indicadores_reportes add column if not exists total_validados integer default 0;
alter table indicadores_reportes add column if not exists total_rechazados integer default 0;
alter table indicadores_reportes add column if not exists total_pendientes integer default 0;
alter table indicadores_reportes add column if not exists created_at timestamptz default now();

do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'usuarios_rol_check') then
    alter table usuarios add constraint usuarios_rol_check check (rol in ('ciudadano', 'gestor', 'administrador')) not valid;
  end if;
  if not exists (select 1 from pg_constraint where conname = 'reportes_urgencia_check') then
    alter table reportes add constraint reportes_urgencia_check check (urgencia in ('baja', 'media', 'alta', 'critica')) not valid;
  end if;
  if not exists (select 1 from pg_constraint where conname = 'reportes_estado_check') then
    alter table reportes add constraint reportes_estado_check check (estado in ('pendiente', 'validado', 'rechazado', 'atendido', 'archivado')) not valid;
  end if;
  if not exists (select 1 from pg_constraint where conname = 'historial_reportes_accion_check') then
    alter table historial_reportes add constraint historial_reportes_accion_check check (accion in ('creacion', 'validacion', 'rechazo', 'cambio_estado', 'asignacion_zona', 'agregar_foto', 'eliminar_foto', 'observacion', 'archivado')) not valid;
  end if;
end $$;

do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'reportes_usuario_id_fkey') then
    alter table reportes add constraint reportes_usuario_id_fkey foreign key (usuario_id) references usuarios(id) not valid;
  end if;
  if not exists (select 1 from pg_constraint where conname = 'reportes_categoria_id_fkey') then
    alter table reportes add constraint reportes_categoria_id_fkey foreign key (categoria_id) references categorias(id) not valid;
  end if;
  if not exists (select 1 from pg_constraint where conname = 'reportes_zona_id_fkey') then
    alter table reportes add constraint reportes_zona_id_fkey foreign key (zona_id) references zonas(id) not valid;
  end if;
  if not exists (select 1 from pg_constraint where conname = 'reportes_validado_por_fkey') then
    alter table reportes add constraint reportes_validado_por_fkey foreign key (validado_por) references usuarios(id) not valid;
  end if;
  if not exists (select 1 from pg_constraint where conname = 'reporte_fotos_reporte_id_fkey') then
    alter table reporte_fotos add constraint reporte_fotos_reporte_id_fkey foreign key (reporte_id) references reportes(id) on delete cascade not valid;
  end if;
  if not exists (select 1 from pg_constraint where conname = 'historial_reportes_reporte_id_fkey') then
    alter table historial_reportes add constraint historial_reportes_reporte_id_fkey foreign key (reporte_id) references reportes(id) on delete cascade not valid;
  end if;
  if not exists (select 1 from pg_constraint where conname = 'historial_reportes_usuario_id_fkey') then
    alter table historial_reportes add constraint historial_reportes_usuario_id_fkey foreign key (usuario_id) references usuarios(id) not valid;
  end if;
  if not exists (select 1 from pg_constraint where conname = 'analisis_kde_categoria_id_fkey') then
    alter table analisis_kde add constraint analisis_kde_categoria_id_fkey foreign key (categoria_id) references categorias(id) not valid;
  end if;
  if not exists (select 1 from pg_constraint where conname = 'analisis_kde_zona_id_fkey') then
    alter table analisis_kde add constraint analisis_kde_zona_id_fkey foreign key (zona_id) references zonas(id) not valid;
  end if;
  if not exists (select 1 from pg_constraint where conname = 'indicadores_reportes_categoria_id_fkey') then
    alter table indicadores_reportes add constraint indicadores_reportes_categoria_id_fkey foreign key (categoria_id) references categorias(id) not valid;
  end if;
  if not exists (select 1 from pg_constraint where conname = 'indicadores_reportes_zona_id_fkey') then
    alter table indicadores_reportes add constraint indicadores_reportes_zona_id_fkey foreign key (zona_id) references zonas(id) not valid;
  end if;
end $$;

create unique index if not exists idx_usuarios_firebase_uid on usuarios(firebase_uid) where firebase_uid is not null;
create unique index if not exists idx_usuarios_email on usuarios(email);
create index if not exists idx_reportes_ubicacion on reportes using gist (ubicacion);
create index if not exists idx_reportes_estado on reportes(estado);
create index if not exists idx_reportes_categoria_id on reportes(categoria_id);
create index if not exists idx_reportes_zona_id on reportes(zona_id);
create index if not exists idx_zonas_geom on zonas using gist (geom);
create index if not exists idx_historial_reportes_reporte_id on historial_reportes(reporte_id);
create index if not exists idx_reporte_fotos_reporte_id on reporte_fotos(reporte_id);
create index if not exists idx_indicadores_reportes_fecha on indicadores_reportes(fecha);

create or replace view vw_reportes_dashboard as
select
  r.id,
  r.usuario_id,
  u.nombre as usuario_nombre,
  r.categoria_id,
  c.nombre as categoria_nombre,
  r.urgencia,
  r.descripcion,
  r.ubicacion,
  st_y(r.ubicacion::geometry) as latitud,
  st_x(r.ubicacion::geometry) as longitud,
  r.direccion_aprox,
  r.estado,
  r.zona_id,
  z.nombre as zona_nombre,
  r.validado_por,
  uv.nombre as validado_por_nombre,
  r.validado_at,
  r.created_at,
  r.updated_at,
  count(rf.id) as total_fotos
from reportes r
left join usuarios u on u.id = r.usuario_id
left join categorias c on c.id = r.categoria_id
left join zonas z on z.id = r.zona_id
left join usuarios uv on uv.id = r.validado_por
left join reporte_fotos rf on rf.reporte_id = r.id
group by r.id, u.nombre, c.nombre, z.nombre, uv.nombre;
