create table if not exists unidades_espaciales (
  id integer generated by default as identity primary key,
  codigo varchar(40) not null unique,
  tamanio_m integer not null,
  geom geometry(MultiPolygon, 4326) not null,
  area_m2 numeric not null,
  created_at timestamptz not null default now(),
  constraint ck_unidades_tamanio check (tamanio_m in (250, 500))
);

create table if not exists unidad_vecinos (
  unidad_id integer not null references unidades_espaciales(id) on delete cascade,
  vecino_id integer not null references unidades_espaciales(id) on delete cascade,
  criterio varchar(20) not null default 'queen',
  primary key (unidad_id, vecino_id),
  constraint ck_unidad_vecino_distinto check (unidad_id <> vecino_id)
);

create index if not exists idx_unidades_espaciales_geom
on unidades_espaciales using gist (geom);

create index if not exists idx_unidad_vecinos_vecino
on unidad_vecinos (vecino_id);

with district as (
  select st_transform(st_unaryunion(st_collect(geom)), 32719) as geom
  from zonas
  where activo and geom is not null
),
sizes as (
  select unnest(array[250, 500])::integer as size_m
),
cells as (
  select
    s.size_m,
    (st_dump(st_collectionextract(st_intersection(g.geom, d.geom), 3))).geom as geom_utm
  from district d
  cross join sizes s
  cross join lateral st_squaregrid(s.size_m, d.geom) g
  where st_intersects(g.geom, d.geom)
),
numbered as (
  select
    size_m,
    row_number() over (
      partition by size_m
      order by st_y(st_centroid(geom_utm)) desc, st_x(st_centroid(geom_utm)) asc
    ) as sequence,
    geom_utm
  from cells
  where st_area(geom_utm) >= 100
)
insert into unidades_espaciales (codigo, tamanio_m, geom, area_m2)
select
  'GRID-' || size_m || '-' || lpad(sequence::text, 4, '0'),
  size_m,
  st_multi(st_transform(geom_utm, 4326)),
  round(st_area(geom_utm)::numeric, 2)
from numbered
on conflict (codigo) do nothing;

insert into unidad_vecinos (unidad_id, vecino_id, criterio)
select a.id, b.id, 'queen'
from unidades_espaciales a
join unidades_espaciales b
  on a.tamanio_m = b.tamanio_m
 and a.id <> b.id
 and st_touches(a.geom, b.geom)
on conflict (unidad_id, vecino_id) do nothing;
